spring:
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 100
        max-wait: 100ms
      shutdown-timeout: 100ms
    host: 192.168.134.66
    port: 6379
    timeout: 8000